# Generated by Django 5.0.6 on 2024-07-08 19:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0004_alter_appoinmenttable_time_alter_medicalhistory_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescribition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default=datetime.time(19, 9, 58, 821075))),
                ('title', models.CharField(max_length=100)),
                ('prescription', models.TextField(max_length=500)),
                ('appoinmenet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.appoinmenttable')),
            ],
        ),
    ]
