# Generated by Django 5.0.6 on 2024-07-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribition',
            name='time',
            field=models.TimeField(default=datetime.time(12, 12, 24, 331812)),
        ),
    ]
