# Generated by Django 5.0.6 on 2024-07-10 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_prescribition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribition',
            name='time',
            field=models.TimeField(default=datetime.time(8, 24, 54, 319414)),
        ),
    ]
