# Generated by Django 5.0.6 on 2024-10-02 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_prescribition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribition',
            name='time',
            field=models.TimeField(default=datetime.time(13, 47, 25, 435555)),
        ),
    ]
