# Generated by Django 5.0.6 on 2024-10-02 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_prescribition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribition',
            name='time',
            field=models.TimeField(default=datetime.time(13, 50, 1, 358922)),
        ),
    ]
