# Generated by Django 5.0.6 on 2024-07-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttable',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
