# Generated by Django 5.0.6 on 2024-07-08 02:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Webadmin', '0003_assigndoctor'),
        ('guest', '0003_patienttable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppoinmentTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default=datetime.time(2, 38, 30, 142847))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webadmin.doctortable')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.patienttable')),
            ],
        ),
    ]
