# Generated by Django 5.0.6 on 2024-07-08 03:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('guest', '0003_patienttable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(3, 12, 1, 35650)),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FamilyTree', models.TextField()),
                ('symptoms', models.TextField()),
                ('takingMedication', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('listmedication', models.TextField()),
                ('medicationAllergies', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('usetobacol', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('alcohol', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Never', 'Never'), ('Other', 'Other')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default=datetime.time(3, 12, 1, 35650))),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.patienttable')),
            ],
        ),
    ]
