# Generated by Django 5.0.6 on 2024-07-08 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_appoinmenttable_time_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(3, 43, 2, 265450)),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='listmedication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='time',
            field=models.TimeField(default=datetime.time(3, 43, 2, 265450)),
        ),
    ]
