# Generated by Django 5.0.6 on 2024-07-08 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_appoinmenttable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(19, 9, 58, 820065)),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='time',
            field=models.TimeField(default=datetime.time(19, 9, 58, 821075)),
        ),
    ]
