# Generated by Django 5.0.6 on 2024-07-09 12:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_prescribition_time'),
        ('Patient', '0004_alter_appoinmenttable_time_alter_medicalhistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(12, 12, 24, 330821)),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='time',
            field=models.TimeField(default=datetime.time(12, 12, 24, 330821)),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default=datetime.time(12, 12, 24, 330821))),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.prescribition')),
            ],
        ),
    ]
