# Generated by Django 5.0.6 on 2024-07-10 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_alter_appoinmenttable_time_alter_medicalhistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(8, 24, 54, 319414)),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='time',
            field=models.TimeField(default=datetime.time(8, 24, 54, 319414)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=datetime.time(8, 24, 54, 319414)),
        ),
    ]
