# Generated by Django 5.0.6 on 2024-10-02 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_alter_appoinmenttable_time_alter_medicalhistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(13, 47, 25, 434556)),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='time',
            field=models.TimeField(default=datetime.time(13, 47, 25, 435555)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=datetime.time(13, 47, 25, 435555)),
        ),
    ]
