# Generated by Django 5.0.6 on 2024-10-02 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_alter_appoinmenttable_time_alter_medicalhistory_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.BigIntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(default=datetime.time(13, 50, 1, 357921)),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='time',
            field=models.TimeField(default=datetime.time(13, 50, 1, 357921)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=datetime.time(13, 50, 1, 358922)),
        ),
    ]
