# Generated by Django 5.0.6 on 2024-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
