# Generated by Django 5.0.6 on 2024-07-07 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webadmin', '0002_doctortable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webadmin.departmenttable')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webadmin.doctortable')),
            ],
        ),
    ]
